Traceback (most recent call last):
  File "/home/roberto/Documentos/google-course/upios/6-command-line-shell/interacting-with-the-commmand-line-shell/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
